config/routes.rb
Bt3::Application.routes.draw do

  devise_for :family_accounts, :controllers => { :registrations => :registrations }

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :family_accounts, :only => [:index, :show] do
    resources :child_accounts, :except => [:index]
  end

  resources :child_accounts, :only => [] do
    resources :favorite_foods
  end

  resources :child_accounts, :only => [] do
    resources :favorite_activities
  end

  resources :child_accounts, :only => [] do
    resources :activity_logs, :except => [:new]
  end

  resources :foods, :only => [:index]

  resources :activities, :only => [:index]

  root :to => 'family_accounts#index'

end

app/models/food.rb
class Food < ActiveRecord::Base
	default_scope order('name ASC')

  belongs_to :food_type, 
    :inverse_of => :foods

  validates_presence_of :name
  validates_presence_of :food_type

  attr_accessible :name, :food_type
end

app/models/food_type.rb
class FoodType < ActiveRecord::Base
  has_many :foods, 
    :inverse_of => :food_type
  has_many :favorite_foods, 
    :inverse_of => :food_type

  validates_presence_of :food_type

  attr_accessible :food_type
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  def index
    @search = Food.search(params[:q])
    @foods = @search.result.page(params[:page]).per(params[:limit] || 15)
  end

end

app/views/foods/index.html.erb
<div class='foods'>
  <h2>Food Ideas</h2>
  
  <div id='food-search'>
    <%= search_form_for @search do |f| %>
      <ul>
        <li><%= f.label :name_cont, "Search by Name" %>
          <%= f.text_field :name_cont %></li><br />
        <li><%= f.label :food_type_id_eq, "Filter by Food Type" %>
          <%= f.select :food_type_id_eq, options_from_collection_for_select(FoodType.all, :id, :food_type), 
          :include_blank => 'Please Select' %></li>
        <li><%= label_tag(:limit, "Items to Display") %>
          <%= select_tag :limit, options_for_select([5, 10, 15, 20, 50], selected: params[:limit]), 
          include_blank: true %></li>
        <li><%= f.submit "Submit", class: 'submit' %></li>
        <li><%= link_to 'Clear Search', foods_path, class: 'submit' %></li>
      </ul>
    <% end %>
  </div>

  <table id="food_table">
    <th>Food</th>
    <th>Food Type</th> 
    <th>Add To:</th>
    <%- if current_family_account -%>
      <%- (current_family_account.child_accounts.count - 1).times do -%>
        <th></th>
      <%- end -%>
    <%- end -%> 
    <% @foods.each do |food| %>
      <tr id="food_id_<%= food.id %>">
        <td id='name'><%= food.name %></td>
        <td><%= food.food_type.food_type %></td>
        <% if family_account_signed_in? %>
          <% current_family_account.child_accounts.each do |account| %>
            <%= form_for [account, account.favorite_foods.build] do |f| %>
              <%= f.hidden_field :name, value: food.name %>
              <%= f.hidden_field :food_type_id, value: food.food_type_id %>
              <td><%= f.submit "#{account.username}'s Favs", class: 'fav-link' %></td>
            <% end %>
          <% end %>
        <% else %>
        <td><%= link_to 'Add to Favorites', new_family_account_session_path, class: 'fav-link' %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

<h3><%= paginate @foods %></h3>

<div class='bottom-links'>
  <%- if family_account_signed_in? -%>
    <%- current_family_account.child_accounts.each do |child| -%>
      <%= link_to "#{child.username}'s Favs", child_account_favorite_foods_path(child) %>
    <%- end -%>
  <%- end -%>
</div>