config/routes.rb
Bt3::Application.routes.draw do

  devise_for :family_accounts, :controllers => { :registrations => :registrations }

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :family_accounts, :only => [:index, :show] do
    resources :child_accounts, :except => [:index]
  end

  resources :child_accounts, :only => [] do
    resources :favorite_foods
  end

  resources :child_accounts, :only => [] do
    resources :favorite_activities
  end

  resources :child_accounts, :only => [] do
    resources :activity_logs, :except => [:new]
  end

  resources :foods, :only => [:index]

  resources :activities, :only => [:index]

  root :to => 'family_accounts#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base

  validates_presence_of :activity_category_id
  validates_presence_of :description
  validates_presence_of :name

  belongs_to :activity_category,
    :inverse_of => :activities

  attr_accessible :activity_category_id, :description, :name
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  
  def index
    @search = Activity.search(params[:q])
    @activities = @search.result.page(params[:page]).per(params[:limit] || 15)
  end

end

app/views/activities/index.html.erb
<div class='activities'>
  <h2>Activity Ideas</h2>
  <div id='activity-search'>
    <%= search_form_for @search do |activity| %>
      <ul>
        <li><%= activity.label :name_cont, "Search by Name" %>
          <%= activity.text_field :name_cont %></li>
        <li><%= activity.label :description_cont, "Search by Description" %>
          <%= activity.text_field :description_cont %></li>
        <li><%= activity.label :activity_category_id_eq, "Filter by Category" %>
          <%= activity.select :activity_category_id_eq, options_from_collection_for_select(ActivityCategory.all, :id, :activity_category), 
          :include_blank => 'Please Select' %></li>
        <li><%= label_tag(:limit, "Items to Display") %>
          <%= select_tag :limit, options_for_select([5, 10, 15, 20, 50], selected: params[:limit]), 
          include_blank: true %></li>
        <li><%= activity.submit "Submit", class: 'submit' %></li>
        <li><%= link_to 'Clear Search', activities_path, class: 'submit' %>
      </ul>
    <% end %>
  </div>

  <table id="activity_table">
    <th>Activity</th>
    <th>Category</th>
    <th>Description</th>
    <th>Add To:</th>
    <%- if current_family_account -%>
      <%- (current_family_account.child_accounts.count - 1).times do -%>
        <th></th>
      <%- end -%>
    <%- end -%>
    <% @activities.each do |activity| %>
      <tr id="activity_id_<%= activity.id %>">
        <td id='name'><%= activity.name %></td>
        <td><%= activity.activity_category.activity_category %></td>
        <td><%= activity.description %></td>
        <%- if family_account_signed_in? -%>
          <%- current_family_account.child_accounts.each do |account| -%>
            <%= simple_form_for [account, account.favorite_activities.build] do |f| %>
              <%= f.hidden_field :name, value: activity.name %>
              <%= f.hidden_field :activity_category_id, value: activity.activity_category_id %>
              <%= f.hidden_field :description, value: activity.description %>
              <td><%= f.submit "#{account.username}'s Favs", class: 'fav-link' %></td>
            <%- end -%>
          <%- end -%>
        <%- else -%>  
          <td><%= link_to 'Add to Favorites', new_family_account_session_path, class: 'fav-link' %></td>
        <%- end -%>
      </tr>
    <%end %>
  </table>
</div>
<h3><%= paginate @activities %></h3>
<div class='bottom-links'>
  <%- if family_account_signed_in? -%>
    <%- current_family_account.child_accounts.each do |child| -%>
      <%= link_to "#{child.username}'s Favs", child_account_favorite_activities_path(child) %>
    <%- end -%>
  <%- end -%>
</div>