config/routes.rb
Bt3::Application.routes.draw do

  devise_for :family_accounts, :controllers => { :registrations => :registrations }

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :family_accounts, :only => [:index, :show] do
    resources :child_accounts, :except => [:index]
  end

  resources :child_accounts, :only => [] do
    resources :favorite_foods
  end

  resources :child_accounts, :only => [] do
    resources :favorite_activities
  end

  resources :child_accounts, :only => [] do
    resources :activity_logs, :except => [:new]
  end

  resources :foods, :only => [:index]

  resources :activities, :only => [:index]

  root :to => 'family_accounts#index'

end

app/models/family_account.rb
class FamilyAccount < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :date_of_birth
  validates_presence_of :zip_code

  validates_length_of :zip_code, 
    minimum: 5, 
    message: "Your entry was too short. Please enter at least five characters."
    
  has_many :child_accounts, 
    :inverse_of => :family_account, 
    :dependent => :destroy

  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :date_of_birth, :zip_code
  
end

app/controllers/family_accounts_controller.rb
class FamilyAccountsController < ApplicationController
  before_filter :authenticate_family_account!, :except => [:index]

  def show
    @family_account = current_family_account
  end

end

app/views/family_accounts/index.html.erb
<div class='FFF'>
	<h2>Food, Fitness & Fun for the Whole Family</h2>
	<%- if family_account_signed_in? -%>
		<div class='signed-in'>
		</div>
	<%- else -%>
		<div class='sign-up'>
	  	<%= link_to 'Sign Up Today!', new_family_account_registration_path %>
		</div>
	<%- end -%>
</div>

app/views/family_accounts/show.html.erb
<div class='family-account'>
  <h2>Here is all of your account information:</h2>
 
  <ul id='account-info'>
    <li>Name: <%= @family_account.first_name %> <%= @family_account.last_name %></li>
    <li>Email Address: <%= @family_account.email %></li>
    <li>Date of Birth: <%= @family_account.zip_code %></li>
    <li>Zip Code: <%= @family_account.zip_code %></li><br />
    <li id='add-child'><%= link_to 'Add a Child?', new_family_account_child_account_path(@family_account) %></li><br />
    <li><%= link_to 'Edit My Account', edit_family_account_registration_path %></li>
    <li><%= link_to 'Delete My Account', @family_account, method: :delete, data: { confirm: 'Are you sure? This cannot be undone!' } %></li>
  </ul>

  <% if @family_account.child_accounts.count != 0 %>
    <h2>Below are the children you've registered:</h2>
    <% @family_account.child_accounts.each do |ca| %>
      <ul id='kid-stuff'>
        <li><%= link_to "#{ca.username}'s Favorites", family_account_child_account_path(@family_account, ca) %></li>
      </ul>
    <% end %>
  <% end %>
</div>