config/routes.rb
Bt3::Application.routes.draw do

  devise_for :family_accounts, :controllers => { :registrations => :registrations }

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :family_accounts, :only => [:index, :show] do
    resources :child_accounts, :except => [:index]
  end

  resources :child_accounts, :only => [] do
    resources :favorite_foods
  end

  resources :child_accounts, :only => [] do
    resources :favorite_activities
  end

  resources :child_accounts, :only => [] do
    resources :activity_logs, :except => [:new]
  end

  resources :foods, :only => [:index]

  resources :activities, :only => [:index]

  root :to => 'family_accounts#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html 
  <%- if request.fullpath == family_accounts_path -%>
    class="home-page"
  <%- elsif request.fullpath == root_path -%>
    class="home-page"
  <%- else -%>
    class="basic-background"
  <%- end -%>>

<head>
  <title>Bt3</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Coming+Soon' rel='stylesheet' type='text/css'>
</head>
<body>

<div class="container">

  <header>
    <div class='very-top'>
        <%= link_to image_tag('FF.png'), family_accounts_path, id: 'logo-image' %>
        <%= link_to 'Fit Families', family_accounts_path, id: 'logo-word'  %>
      <div class='signer'>
        <% if family_account_signed_in? %>
          <%= link_to('Log Out', destroy_family_account_session_path, :method => :delete) %>
          <%= link_to 'My Account', family_account_path(current_family_account) %>
          <%- if current_family_account.admin -%>
            <%= link_to 'Admin', rails_admin_path %>
          <%- end -%>

          <br />
          <b>Signed in: <%= current_family_account.email %></b><br />
          <b><%= notice %><%= alert %></b>
        <% else %>
          <%= link_to('Log In', new_family_account_session_path)  %><br />
          <b><%= notice %><%= alert %></b><br />
        <% end %>
      </div>
    </div>
  </header>

  <div class='kids'>
    <% if family_account_signed_in? %>
      <% current_family_account.child_accounts.each do |child| %>
        <%= link_to child.username, family_account_child_account_path(current_family_account, child), class: 'kid-button' unless child.new_record? %>
      <% end %>
    <% end %>
  </div>  

  <div class='nav'>
    <div id="food">
      <%= link_to image_tag('fruit.png'), foods_path %>
    </div>
    <div id="fitness">
      <%= link_to image_tag('balls.png'), activities_path %>
    </div>
  </div>


  <%= yield %>


</div>

<%= javascript_include_tag 'layout' %>
</body>
<footer
  <%- if request.fullpath == family_accounts_path -%>
    class="none"
  <%- elsif request.fullpath == root_path -%>
    class="none"
  <%- else -%>
    class="footer"
  <%- end -%>>
  <%= link_to image_tag('soccer.png'), activities_path, id: 'foot-activity' %>
  <%= link_to image_tag('food_at_bottom.png'), foods_path, id: 'foot-food' %>
</footer>
<div 
  <%- if request.fullpath == family_accounts_path -%>
    class="none"
  <%- elsif request.fullpath == root_path -%>
    class="none"
  <%- else -%>
    id="very-bottom"
  <%- end -%>>
</div>
</html>